### ISSUE TITLE
can I use it with VFD?

### ISSUE THREAD

**Issue by bernid** [matejx/ser2hd44780#1]
Hi, 
Can I use this project to drive hd44780 compatible VFD display?
For example:
https://noritake-vfd.com/cu20029-uw1j.aspx
What about dimmer setings?
Regards,

**Comment by matejx** [comment]
Since the interface claims to be hd44780 compatible I don't see why not.

I don't know how brightness is controlled on a VFD display and access to the full datasheet requires entering personal information.

**Comment by bernid** [comment]
Thanks. 
Please find  the link (datasheet) :
https://www.dropbox.com/s/8eyxom2kqhjiuh3/s-cu20029-uw1j_e00.pdf?raw=1

**Comment by matejx** [comment]
OK, so the brightness of the VFD is set with a command, unlike an LCD where the contrast is set with voltage on a pin. It does this by using a bit of trickery - a data byte sent immediately after the Set Function command is interpreted as a brightness value.

The ser2hd44780 interface already uses some of the non printable ASCII characters (0..32) as commands. You could add 4 commands to set the corresponding 4 possible brightness values (25%, 50%, 75%, 100%) like this:

```
					case 0x0d:	// cr
						lcd_endl();
						break;
					case 0x0a:	// lf
						lcd_line(cl);
						break;
					case 0x10: // VFD brightness
					case 0x11:
					case 0x12:
					case 0x13:
						lcd_wr(0x30, 0); // function set command
						lcd_wr(c - 0x10, 1); // brightness control
						break;
				}
			} else {
				lcd_putc(c);
			}
```

**Comment by bernid** [comment]
Thanks a lot!
I'm going to experiment.
